Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "csaidiS" do |master|
    master.vm.hostname = "csaidiS"

    master.vm.network "private_network", ip: "192.168.56.110"

    master.vm.provider "virtualbox" do |vb|
      vb.name = "csaidiS"
      vb.memory = 2048
      vb.cpus = 2
    end

    master.vm.provision "shell", path: "./scripts/server_setup.sh"

    master.vm.synced_folder "./confs", "/confs"
  end
end
