Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "aakhrifS" do |master|
    master.vm.hostname = "aakhrifS"

    master.vm.network "private_network", ip: "192.168.56.110"

    master.vm.provider "virtualbox" do |vb|
      vb.name = "aakhrifS"        # Preferred way to name the VM
      vb.memory = 1024              # Allocate 1 GB RAM
      vb.cpus = 2                   # Use 2 CPU cores
    end

    master.vm.provision "shell", path: "./scripts/server_setup.sh"

    master.vm.synced_folder "./confs", "/confs"  # safer to use a subfolder than "/"
  end
end
