Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"  # Ubuntu 20.04

  config.vm.define "aakhrifS" do |master|
    master.vm.hostname = "aakhrifS"
    master.vm.network "private_network", ip: "192.168.56.110", virtualbox__intnet: "eth1"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--name", "aakhrifS"]
    end
    master.vm.provision "shell", path: "server_setup.sh"
  end

  config.vm.define "aakhrifSW" do |worker|
    worker.vm.hostname = "aakhrifSW"
    worker.vm.network "private_network", ip: "192.168.56.111", virtualbox__intnet: "eth1"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--name", "aakhrifSW"]
    end
    worker.vm.provision "shell", path: "worker_setup.sh"
  end

end
