Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "aakhrifS" do |master|
    master.vm.hostname = "aakhrifS"
    master.vm.network "private_network", ip: "192.168.56.110", virtualbox__intnet: "eth1"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    master.vm.provision "shell", path: "./scripts/server_setup.sh"
  end

  config.vm.define "aakhrifSW" do |worker|
    worker.vm.hostname = "aakhrifSW"
    worker.vm.network "private_network", ip: "192.168.56.111", virtualbox__intnet: "eth1"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    worker.vm.provision "shell", path: "./scripts/worker_setup.sh"
  end

end
